### PR TITLE
Eclipse Collections support

### PR DESCRIPTION
**Pull request by yawkat**
See #29

### CODE REVIEW

**Comment by cowtowncoder** [comment]
As per discussions, receiving CLA, would be happy to merge. Just one last (?) question: what'd be the simplest way to get this to merge against `2.9` branch? I am ok with `master`, but it seems better to allow 2.x users to use this as 3.0 will take a while.

**Comment by yawkat** [comment]
My changes are against 2.9 (see [network graph](https://github.com/yawkat/jackson-datatypes-collections/network)) from what I can tell.

Do you know why travis is failing? It works fine locally, is this just a travis oddity for developing a SNAPSHOT?

**Comment by cowtowncoder** [comment]
@yawkat Hmmh. For me, UI claims "yawkat wants to merge 7 commits into FasterXML:master from yawkat:eclipse-collections-0" -- not sure where the discrepancy comes from?

**Comment by cowtowncoder** [comment]
As to build failure: I think I know what is causing it. Only lately realized that snapshot repository settings can not be included via parent pom, if snapshot of parent pom is needed.... so I added settings in `2.9`; if you merge I think that'll fix Travis build.

**Comment by yawkat** [comment]
Oh I see. I developed against 2.9 but made the PR into master instead. Fixed :)

**Comment by cowtowncoder** [comment]
Merged in; also merged up to master and made changes needed to compiled again (due to API changes).

**Pull request merged**
