### PR TITLE
Issue #20 Guava deserialization not working when object to deserializ…

### PR DESCRIPTION
**Pull request by digitalillusion**
Fixes issue #20

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Have you tested that this would work?

**Comment by digitalillusion** [comment]
I've added unit tests. Note that the error message is different when unit testing the old code, but the issue is exactly that isAssignableFrom returns false

**Comment by cowtowncoder** [comment]
@digitalillusion I guess my question was more about what exactly is the goal here, since there are 2 possibilities:

1. Trying to make things work with presence of possibly multiple copies of Guava (via diff `ClassLoader`s)
2. Give more informative error message in case multiple copies cause mismatch

It sounds more like this would be (2)? If so that's fine if and when it'd help users recognize the problem. I just want to make sure I understand what is being done.

**Comment by cowtowncoder** [comment]
... but actually even with that I don't like the approach. I don't think class names and lookups should go back and forth, in order to try to look for specific error condition. It just seems like a hacky way to detect a (relatively) rare problem.

**Comment by digitalillusion** [comment]
Hi @cowtowncoder 
I understand that the situation under which the deserializer and the classes to deserialize are loaded by the same classloader is the most common. In my case the issue occured under OSGi environment, where the aforementioned situation may not sussist.
I agree that the proposed fix might not be optimal, maybe it would be better to chain the classloaders instead, but in any case I just wanted to expose the problem.
Feel free to close the merge request if you don't think it's worth a fix.

**Comment by cowtowncoder** [comment]
@digitalillusion I think I would have no trouble if the behavior was a feature of module, disabled by default. That is, if there's a way to configure module to use it (or not).

Guava module already has one configurable aspect (see `GuavaModule`, `_cfgHandleAbsentAsNull`), and this could follow same approach (for 3.0 I may convert these to specific `GuavaFeature` enum, but first things first).

If this could be done, I'd have no objections, and can merge it for `2.9.6`, given that it'll be last 2.x version (usually it'd go in next minor version).

**Comment by digitalillusion** [comment]
Since there is no widespread interest for this scenario, I'm closing the pull request

**Pull request closed without merging**
