### PR TITLE
try to fix [ #106 ](https://github.com/FasterXML/jackson-datatypes-collections/issues/106)

### PR DESCRIPTION
**Pull request by magical-l**
try to fix [ #106 ](https://github.com/FasterXML/jackson-datatypes-collections/issues/106)

### CODE REVIEW

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Makes sense, would be happy to merge this.

Before merging I do need one more thing: CLA (if I haven't asked for one before -- it only needs to be sent once and is good for all future contributions).
It's from here:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and the usual way is to fill it, sign, scan/photo, email to `info` at fasterxml dot com.

Once I have it I'll merge this PR.

Thank you again for contributing it; looking forward to merge!

**Comment by magical-l** [comment]
@cowtowncoder how can I fill and sign the pdf you mentioned? do it on the pdf? or whatever format contains the all words?

**Comment by magical-l** [comment]
@cowtowncoder ok, I'll print the pdf, fill, sign, take a photo with mobile, and email to the address. is it ok?

**Comment by cowtowncoder** [comment]
@magical-l Usually you do not modify PDF, but print a copy, fill in paper version, scan (or take a photo).

But if you prefer, editing PDF works too; this has been done by some contributors. There are free tools for doing that.
Either way works fine.

**Comment by cowtowncoder** [comment]
Yes, that works fine.

**Comment by cowtowncoder** [comment]
> @cowtowncoder ok, I'll print the pdf, fill, sign, take a photo with mobile, and email to the address. is it ok?

Yes, that's perfect.

**Comment by magical-l** [comment]
@cowtowncoder oh no...I found the email was rejected... sent from my email lwj621 at 163 dot com

> The response was:
> Your email to group [info@fasterxml.com](mailto:info@fasterxml.com) was rejected due to spam classification. The owner of the group can choose to enable message moderation instead of bouncing these emails. More information can be found here: https://support.google.com/a/answer/168383.

**Comment by cowtowncoder** [comment]
@magical-l That is unfortunate. I don't have anything set up on my side to block that domain.

Maybe you can sending this directly to my alias "tatu" at fasterxml dot com, and see if that works better. If not, I can share my secondary email.

**Comment by cowtowncoder** [comment]
CLA received! Can now just merge.

**Review by cowtowncoder — APPROVED** [review]

**Pull request merged**
